services:
  db:
    image: motorway-test-backend
    container_name: db
    build:
      context: .
      dockerfile: ./db.Dockerfile
      target: motorway-test-backend
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - default
  api:
    image: api-dev
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: ./api.Dockerfile
      target: api-dev
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/src/app
    env_file: .env
    networks:
      - default

networks:
  default: