services:
  db:
    image: motorway-test-backend
    container_name: db
    build:
      context: .
      dockerfile: ./db.Dockerfile
      target: motorway-test-backend
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway
    ports:
      - 5432:5432
  api:
    image: api-dev
    container_name: api
    restart: always
    build:
      context: .
      dockerfile: ./api.Dockerfile
      target: api-dev
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
    - .:/usr/app
    environment:
      - PORT=3000
      - POSTGRES_HOST=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=motorway