name: docker-compose-actions-workflow
on: push
jobs:
  BuildAndTest:
    runs-on: ubuntu-latest
    env:
      PORT: 3000
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: motorway
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Build the stack
        run: docker-compose up -d
      - name: Lint
        run: docker run --rm -i api-dev yarn lint
      - name: Unit Test
        run: docker run --rm -i api-dev yarn test
      - name: Integration Test
        run: docker run --rm --network host -e PORT=3000 -e POSTGRES_HOST=0.0.0.0 -e POSTGRES_USER=user -e POSTGRES_PASSWORD=password -e POSTGRES_DB=motorway -i api-dev yarn test:integration